name: Deploy GUI to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create SSH key file
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Copy project files to EC2 (excluding .git)
        run: |
            rsync -avz -e "ssh -i private_key.pem -o StrictHostKeyChecking=no" --exclude='.git' ./ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/InSpectRail/

      - name: Deploy on EC2 with systemd
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/InSpectRail/

            # Stop services if running
            sudo systemctl stop mysite.service || true

            # Install python3-venv if not available
            sudo apt-get update
            sudo apt-get install -y python3-venv libgl1

            # Setup virtual environment
            python3 -m venv inspectrail
            source inspectrail/bin/activate

            # Upgrade pip and install requirements
            pip install --upgrade pip
            pip install -r requirements.txt

            # Move and fix systemd service file (ensure it's valid)
            sudo mv mysite.service /etc/systemd/system/

            # Reload and enable systemd services
            sudo systemctl daemon-reexec
            sudo systemctl daemon-reload
            sudo systemctl enable mysite.service

            # Start the service
            sudo systemctl restart mysite.service

            echo "✅ Deployment completed using systemd services."